---
- hosts: switches
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ vault_switch_username }}"
      password: "{{ vault_switch_password }}"

  tasks:
      - name: run show version
        nxos_command:
          commands: "show version"
          host: "{{ inventory_hostname }}"
          username: admin
          password: admin
        register: show_version

      - name: print the show debug output
        debug: var=show_version
