---
- hosts: switches
  connection: local
  vars:
    cli:
      host: "{{ ansible_hostname }}"
      username: admin
      password: admin
      transport: cli

  tasks:
      - name: run show version
        nxos_command:
          commands: "show version"
          provider: "{{ cli }}"

        register: show_version

      - name: print the show debug output
        debug: var=show_version
